//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_1280x720 {
            get {
                object obj = ResourceManager.GetObject("Background_1280x720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_800x600 {
            get {
                object obj = ResourceManager.GetObject("Background_800x600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bicarbonate_Of_Soda {
            get {
                object obj = ResourceManager.GetObject("Bicarbonate_Of_Soda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Butter {
            get {
                object obj = ResourceManager.GetObject("Butter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButteredCaketin {
            get {
                object obj = ResourceManager.GetObject("ButteredCaketin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttermilk {
            get {
                object obj = ResourceManager.GetObject("Buttermilk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CakeTinFull {
            get {
                object obj = ResourceManager.GetObject("CakeTinFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use this item now..
        /// </summary>
        internal static string CANT_UNBIND {
            get {
                return ResourceManager.GetString("CANT_UNBIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use this item on its self. Make sure you are clicking the correct object..
        /// </summary>
        internal static string CANT_USE_ITSELF {
            get {
                return ResourceManager.GetString("CANT_USE_ITSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chocolate_bar_full {
            get {
                object obj = ResourceManager.GetObject("chocolate_bar_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chocolate_bar_half {
            get {
                object obj = ResourceManager.GetObject("chocolate_bar_half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cocoa {
            get {
                object obj = ResourceManager.GetObject("Cocoa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoolingRack {
            get {
                object obj = ResourceManager.GetObject("CoolingRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoolingRackChocolated {
            get {
                object obj = ResourceManager.GetObject("CoolingRackChocolated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cup_Flower {
            get {
                object obj = ResourceManager.GetObject("Cup_Flower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoubleCream {
            get {
                object obj = ResourceManager.GetObject("DoubleCream", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Egg {
            get {
                object obj = ResourceManager.GetObject("Egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eggbox_One {
            get {
                object obj = ResourceManager.GetObject("Eggbox_One", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eggbox_Three {
            get {
                object obj = ResourceManager.GetObject("Eggbox_Three", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eggbox_Two {
            get {
                object obj = ResourceManager.GetObject("Eggbox_Two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmptyCaketin {
            get {
                object obj = ResourceManager.GetObject("EmptyCaketin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flour {
            get {
                object obj = ResourceManager.GetObject("Flour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Butter {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Butter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Chocolate {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Chocolate_Butter {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Chocolate_Butter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Cream_Chocolate {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Cream_Chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Flower {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Flower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Flower_Cocoa {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Flower_Cocoa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Flower_Cocoa_Eggs {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Flower_Cocoa_Eggs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Bowl_Flower_Egg {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Bowl_Flower_Egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Mixed {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Mixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glass_Mixing_Mixed_Melted {
            get {
                object obj = ResourceManager.GetObject("Glass_Mixing_Mixed_Melted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream High_On_Hover {
            get {
                return ResourceManager.GetStream("High_On_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InstantCoffee {
            get {
                object obj = ResourceManager.GetObject("InstantCoffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter the Cake Tin..
        /// </summary>
        internal static string INSTRUCTION_1 {
            get {
                return ResourceManager.GetString("INSTRUCTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour Melting Bowl into Cake Tin, bake for 90 Minutes on 140C..
        /// </summary>
        internal static string INSTRUCTION_10 {
            get {
                return ResourceManager.GetString("INSTRUCTION_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut cake into three horizontal slices..
        /// </summary>
        internal static string INSTRUCTION_11 {
            get {
                return ResourceManager.GetString("INSTRUCTION_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chop 200g chocolate into a bowl, pour 300ml Double Cream on top. Heat in oven until melted..
        /// </summary>
        internal static string INSTRUCTION_12 {
            get {
                return ResourceManager.GetString("INSTRUCTION_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer the cakes with covering, pour rest on top of the cake..
        /// </summary>
        internal static string INSTRUCTION_13 {
            get {
                return ResourceManager.GetString("INSTRUCTION_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 200g chocolate into a Melting Bowl..
        /// </summary>
        internal static string INSTRUCTION_2 {
            get {
                return ResourceManager.GetString("INSTRUCTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut 200g butter into pieces, place in Melting Bowl..
        /// </summary>
        internal static string INSTRUCTION_3 {
            get {
                return ResourceManager.GetString("INSTRUCTION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tablespoon of Instant Coffee into 125ml cold water, place in Melting Bowl..
        /// </summary>
        internal static string INSTRUCTION_4 {
            get {
                return ResourceManager.GetString("INSTRUCTION_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat until melted in the Oven.
        /// </summary>
        internal static string INSTRUCTION_5 {
            get {
                return ResourceManager.GetString("INSTRUCTION_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix 170g of flour, 1/4 bicarbonate of soda, 300g sugar and 25g cocoa powder in Mixing Bowl..
        /// </summary>
        internal static string INSTRUCTION_6 {
            get {
                return ResourceManager.GetString("INSTRUCTION_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 3 Medium Eggs in a bowl, pour in 75ml Buttermilk..
        /// </summary>
        internal static string INSTRUCTION_7 {
            get {
                return ResourceManager.GetString("INSTRUCTION_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour melted chocolate into Mixing Bowl.
        /// </summary>
        internal static string INSTRUCTION_8 {
            get {
                return ResourceManager.GetString("INSTRUCTION_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix until smooth.
        /// </summary>
        internal static string INSTRUCTION_9 {
            get {
                return ResourceManager.GetString("INSTRUCTION_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Knife {
            get {
                object obj = ResourceManager.GetObject("Knife", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Low_On_Hover {
            get {
                return ResourceManager.GetStream("Low_On_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marker {
            get {
                object obj = ResourceManager.GetObject("Marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no interaction between these two items.
        /// </summary>
        internal static string NO_INTERACTION {
            get {
                return ResourceManager.GetString("NO_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These items aren&apos;t ready to be mixed..
        /// </summary>
        internal static string NOT_READY {
            get {
                return ResourceManager.GetString("NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oven {
            get {
                object obj = ResourceManager.GetObject("oven", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Oven_Alarm {
            get {
                return ResourceManager.GetStream("Oven_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oven_off_with_cake {
            get {
                object obj = ResourceManager.GetObject("oven_off_with_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oven_on {
            get {
                object obj = ResourceManager.GetObject("oven_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oven_on_smoking {
            get {
                object obj = ResourceManager.GetObject("oven_on_smoking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oven_on_with_cake {
            get {
                object obj = ResourceManager.GetObject("oven_on_with_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream OvenOnSound {
            get {
                return ResourceManager.GetStream("OvenOnSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scales {
            get {
                object obj = ResourceManager.GetObject("Scales", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sink {
            get {
                object obj = ResourceManager.GetObject("Sink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashBackground {
            get {
                object obj = ResourceManager.GetObject("SplashBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sugar {
            get {
                object obj = ResourceManager.GetObject("Sugar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaterJugEmpty {
            get {
                object obj = ResourceManager.GetObject("WaterJugEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaterJugFull {
            get {
                object obj = ResourceManager.GetObject("WaterJugFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaterJugFullCoffee {
            get {
                object obj = ResourceManager.GetObject("WaterJugFullCoffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk {
            get {
                object obj = ResourceManager.GetObject("Whisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
